apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: 192.168.0.215  # Remplace par l'IP statique réservée