apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "192.168.0.201"  # Adresse IP du master principal
  bindPort: 6443
nodeRegistration:
  name: "k8s01-1"  # Nom du nœud principal (master)
  criSocket: "/var/run/containerd/containerd.sock"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: "1.32.2"
controlPlaneEndpoint: "k8s:6443"  # Point de terminaison du Load Balancer (IP virtuelle partagée)
networking:
  podSubnet: "11.0.0.0/16"  # Subnet pour les pods
  serviceSubnet: "10.0.0.0/16"  # Subnet pour les services
apiServer:
  certSANs:
    - "k8s"
    - "k8s01-1"
    - "k8s01-2"
    - "k8s01-3"
    - "192.168.0.200"
    - "192.168.0.201"
    - "192.168.0.202"
    - "192.168.0.203"
    - "localhost"
etcd:
  local:
    dataDir: "/var/lib/etcd"
    certSANs:
      - "k8s"
      - "k8s01-1"
      - "k8s01-2"
      - "k8s01-3"
      - "192.168.0.200"
      - "192.168.0.201"
      - "192.168.0.202"
      - "192.168.0.203"
      - "localhost"
      - "127.0.0.1"
      - "::1"
controllerManager: {}
scheduler: {}
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: "systemd"
