apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: external-ips
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.210-192.168.0.240
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: external-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - external-ips
  # NOTE: L'interface réseau est détectée automatiquement par install-metallb.sh
  # Exemples d'interfaces courantes: ens33, ens18, enp0s3, eth0
  # Pour détecter votre interface: ip route | grep default | awk '{print $5}'
  interfaces:
  - ens33  # Remplacez par votre interface détectée
