apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: external-ips
  namespace: metallb-system
spec:
  addresses:
  # ⚠️ IMPORTANT: Cette plage NE DOIT PAS chevaucher les IPs des nœuds
  # Nœuds utilisent: .200 (VIP), .201-.203 (Masters), .211-.213 (Workers)
  # Plage disponible: .220-.240 (21 IPs pour services LoadBalancer)
  - 192.168.0.220-192.168.0.240
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: external-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - external-ips
  # NOTE: L'interface réseau est détectée automatiquement par install-metallb.sh
  # Exemples d'interfaces courantes: ens33, ens18, enp0s3, eth0
  # Pour détecter votre interface: ip route | grep default | awk '{print $5}'
  interfaces:
  - ens33  # Remplacez par votre interface détectée
